/////////////
// Imports //
/////////////
#import "@preview/adaptable-pset:0.2.0": *
#import "@preview/physica:0.9.8": *
#import "@preview/unify:0.8.1": *
#import "@preview/codly:1.3.0": *
#import "@preview/codly-languages:0.1.1": *
#show: codly-init.with()
#codly(languages: codly-languages)

/////////////////
// Maths Setup //
/////////////////

// upright vectors
#let vectorboldupright(a) = vb($upright(#a)$)
#let vbu = vectorboldupright
#let vectorunitupright(a) = vu($upright(#a)$)
#let vuu = vectorunitupright
#let vectorarrowupright(a) = va($upright(#a)$)
#let vau = vectorarrowupright

// automatically use square brackets for vectors and matricies
#set math.vec(delim: "[")
#set math.mat(delim: "[")
#let vecrowOld = vecrow
#let vecrow = vecrowOld.with(delim: "[")

// Read numerical results generated by src/index.py.
#let result(part, name) = {
    let prefix = name + " = "
    let line = read("../outputs/text/s" + part + ".txt")
        .split("\n")
        .find(line => line.starts-with(prefix))
    line.slice(prefix.len()).split(" ").first().replace("-", "−")
}

////////////////////
// Document Setup //
////////////////////

// assignment info
#show: homework.with(
    title: "HW03",
    author: "Vai Srivastava",
    collaborators: [],
    course-id: "ENAE 601: Astrodynamics",
    instructor: "Dr. Healy",
    semester: "Fall 2026",
    due-time: datetime(
        // due date
        year: 2026,
        month: 10,
        day: 07,

        // due time
        hour: 23,
        minute: 59,
        second: 00,
    ).display(
        "[month repr:long] [day padding:zero], [year] at [hour repr:24]:[minute padding:zero]:[second padding:zero]",
    ),

    // (defaults to A4)
    paper-size: "us-letter",
)

// document settings
#set text(font: "New Computer Modern", size: 10pt)
#set enum(numbering: "a)")

// problem headings
#let probOld = prob
#let prob = prob.with(color: black)

////////////////////////////
// The Assignment Itself: //
// Problems and Solutions //
////////////////////////////

// NOTE: Where classical orbital elements are requested, use standard orbital elements with semimajor axis $a$---not angular momentum magnitude $h$---as per #link("HW02")[../../hw02/reports/main.typ]

#prob(title: "Curtis 4.3")[
    For a geocentric satellite whose inertial position and velocity vectors in a geocentric equatorial frame are:
    $
        vbu(r) = & 2500 vuu(I) & +16000 vuu(J) & +4000 vuu(K) &   space (unit("km")) \
        vbu(v) = & -3 vuu(I)   &       -vuu(J) & +5 vuu(K)    & space (unit("km/s"))
    $

    + Find the classical orbital elements $e$, $a$, $i$, $Omega$, $omega$, $theta$.
    <hwk:p01a>

    + Compute the equinoctial orbital elements $a$, $h$ #emph[(this is not angular momentum)], $k$, $p$ #emph[(this is not semilatus rectum)], $q$, $lambda$.
    <hwk:p01b>
] <hwk:p01>

+ To distinguish angular momentum from the equinoctial element $h$, define:
    $
        vbu(H) & = vbu(r) times vbu(v) \
             H & = abs(vbu(H)).
    $

    The node vector, eccentricity vector, and specific energy are:
    $
        vbu(N) & = vuu(K) times vbu(H), \
        vbu(e) & = (vbu(v) times vbu(H))/mu - vbu(r)/r, \
        cal(E) & = v^2/2-mu/r, \
             a & =-mu/(2 cal(E)).
    $

    Substituting the given state gives:
    $
        vbu(H) & = vecrow(84000, -24500, 45500) space (unit("km^2/s")), \
        vbu(N) & = vecrow(24500, 84000, 0) space (unit("km^2/s")), \
        vbu(e) & = vecrow(0.0433034541, 0.4369514387, 0.1553367056), \
        cal(E) & = qty(result("01a", "energy"), "km^2/s^2").
    $

    To retain the correct quadrants, the oriented angle is:
    $
        A(vbu(x), vbu(y)) = op("atan2")(
            vuu(H) dot (vbu(x) times vbu(y)), vbu(x) dot vbu(y)
        ), quad vuu(H)=vbu(H)/H.
    $

    Reduce angles $mod 2pi$ into $[0, 2pi)$. Thus:
    $
            i & = arccos(H_z/H), \
        Omega & = op("atan2")(N_y,N_x), \
        omega & = A(vbu(N),vbu(e)), \
        theta & = A(vbu(e),vbu(r)).
    $

    Here $v_r=(vbu(r) dot vbu(v))/r=qty(result("01a", "vr"), "km/s")<0$, so the satellite is approaching perigee and $theta>qty(180, "degree")$.

    #colbreak(weak: true)

    Thus, the classical orbital elements are:
    $
            e & = #result("01a", "e"), \
            a & = qty(result("01a", "a"), "km"), \
            i & = qty(result("01a", "i"), "degree"), \
        Omega & = qty(result("01a", "Omega"), "degree"), \
        omega & = qty(result("01a", "omega"), "degree"), \
        theta & = qty(result("01a", "theta"), "degree") quad qed
    $
<hwk:s01a>

+ Use the equinoctial convention:
    $
             h & = e sin(Omega+omega), \
             k & = e cos(Omega+omega), \
             p & = tan(i/2) sin(Omega), \
             q & = tan(i/2) cos(Omega), \
        lambda & = Omega+omega+M.
    $ <eqn:equinoctial>

    Here $a$ is unchanged, $h,k,p,q$ are dimensionless, and $lambda$ is mean longitude.

    Obtain the mean anomaly from:
    $
        E & = op("atan2")(sqrt(1-e^2) sin(theta), e+cos(theta)), \
        M & = E-e sin(E),
    $ <eqn:anomalies>
    reducing $E$, $M$, and $lambda$ via $mod 2pi$.

    Noting that all anomaly calculations use radians, substitution and conversion gives:
    $
        E & = qty(result("01a", "E"), "degree") \
        M & = qty(result("01a", "M"), "degree").
    $

    Thus, the equinoctial orbital elements are:
    $
             a & = qty(result("01b", "a"), "km"), \
             h & = #result("01b", "h"), \
             k & = #result("01b", "k"), \
             p & = #result("01b", "p"), \
             q & = #result("01b", "q"), \
        lambda & = qty(result("01b", "lambda"), "degree") quad qed
    $
<hwk:s01b>

#pagebreak(weak: true)

#prob(title: "Curtis 4.4")[
    At a given instant, the position $vbu(r)$ and velocity $vbu(v)$ of a satellite in the geocentric equatorial frame are:
    $
        vbu(r) & =          &           & -13000 vuu(K) &   space (unit("km")) \
        vbu(v) & = 4 vuu(I) & +5 vuu(J) & +6 vuu(K)     & space (unit("km/s"))
    $

    + Find the classical orbital elements $e$, $a$, $i$, $Omega$, $omega$, $theta$.
    <hwk:p02a>

    + Compute the equinoctial orbital elements $a$, $h$ #emph[(this is not angular momentum)], $k$, $p$ #emph[(this is not semilatus rectum)], $q$, $lambda$.
    <hwk:p02b>
] <hwk:p02>

+ Using the state-to-elements relations from #link(<hwk:s01a>)[Problem 1, Part A],
    $
        vbu(H) & = vecrow(65000, -52000, 0) space (unit("km^2/s")), \
        vbu(N) & = vecrow(52000, 65000, 0) space (unit("km^2/s")), \
        vbu(e) & = vecrow(0.7827395886, 0.9784244857, -0.3371801305), \
        cal(E) & = qty(result("02a", "energy"), "km^2/s^2").
    $

    The positive specific energy and $e>1$ identify a hyperbola, with signed semimajor axis $a=-mu/(2 cal(E))<0$.

    Since $H_z=0$, the orbit is polar: $i=qty(90, "degree")$. Although $v_z>0$, the satellite is below the equatorial plane and moving inward:
    $
        v_r=(vbu(r) dot vbu(v))/r=qty(result("02a", "vr"), "km/s")<0.
    $

    Thus, the signed true anomaly is negative. Evaluating the oriented angles and reporting $theta$ in $[0,2pi)$ gives:
    $
            e & = #result("02a", "e"), \
            a & = qty(result("02a", "a"), "km"), \
            i & = qty(result("02a", "i"), "degree"), \
        Omega & = qty(result("02a", "Omega"), "degree"), \
        omega & = qty(result("02a", "omega"), "degree"), \
        theta & = qty(result("02a", "theta"), "degree") quad qed
    $

    Equivalently, $theta=qty(result("02a", "theta_signed"), "degree")$ on the physical hyperbolic branch, $-arccos(-1/e)<theta<arccos(-1/e)$, consistent with approach to perigee.
<hwk:s02a>

+ The definitions of $h,k,p,q$ in #link(<eqn:equinoctial>)[Problem 1, Part B] still describe the eccentricity vector and orbital plane. With $tan(i/2)=1$:
    $
        p & = sin(Omega)=5/sqrt(41), \
        q & = cos(Omega)=4/sqrt(41).
    $

    The elliptic eccentric anomaly $E$ and the formulas involving $sqrt(1-e^2)$ do not apply. Instead, use the signed hyperbolic eccentric anomaly $F_h$ and hyperbolic mean anomaly $M_h$:
    $
        F_h & = op("arsinh")((sqrt(e^2-1) sin(theta))/(1+e cos(theta))) \
            & = #result("02a", "F"), \
        M_h & = e sinh(F_h)-F_h=#result("02a", "M_h").
    $

    These are dimensionless, unbounded quantities, meaning both are negative before perigee. In particular, $M_h=sqrt(mu/(-a)^3)(t-t_p)$, where $t_p$ is the time of perigee passage.

    To retain the requested mean-longitude element, explicitly extend its definition to the hyperbola:
    $
        pi.alt & = (Omega+omega) mod 2pi \
               & = qty(result("02a", "varpi"), "degree"), \
        lambda & = pi.alt+M_h.
    $

    Here $pi.alt$ is fixed in $[0,2pi)$ and converted to radians before adding $M_h$. Neither $M_h$ nor $lambda$ is reduced $mod 2pi$, as doing so would lose the position along the nonperiodic trajectory. This is a hyperbolic extension of the equinoctial elements, so the elliptic eccentric-longitude equations used for the other problems are unfortunately inapplicable.

    With this convention, the elements are:
    $
             a & = qty(result("02b", "a"), "km"), \
             h & = #result("02b", "h"), \
             k & = #result("02b", "k"), \
             p & = #result("02b", "p"), \
             q & = #result("02b", "q"), \
        lambda & = qty(result("02b", "lambda"), "degree") quad qed
    $

    As a check, solving $e sinh(F_h)-F_h=lambda-pi.alt$ and reconstructing the inertial state recovers $vbu(r)=vecrow(0, 0, -13000) space unit("km")$ and $vbu(v)=vecrow(4, 5, 6) space unit("km/s")$ to numerical precision (an implementation of this can be seen in the #link("https://github.com/vaisriv/enae601-hw03/blob/main/src/index.py#L357")[Python code for this problem]).
<hwk:s02b>

#pagebreak(weak: true)

#prob(title: "Curtis 4.5")[
    At time $t_0$ (relative to perigee passage) the position $vbu(r)$ and velocity $vbu(v)$ of a satellite in the geocentric equatorial frame are:
    $
        vbu(r) & = 6500 vuu(I) & -7500 vuu(J) & -2500 vuu(K) &   space (unit("km")) \
        vbu(v) & = 4 vuu(I)    &    +3 vuu(J) & -3 vuu(K)    & space (unit("km/s"))
    $

    + Find the classical orbital elements $e$, $a$, $i$, $Omega$, $omega$, $theta$.
    <hwk:p03a>

    + Compute the equinoctial orbital elements $a$, $h$ #emph[(this is not angular momentum)], $k$, $p$ #emph[(this is not semilatus rectum)], $q$, $lambda$.
    <hwk:p03b>
] <hwk:p03>

+ The angular momentum, node vector, eccentricity vector, and energy are:
    $
        vbu(H) & = vecrow(30000, 9500, 49500) space (unit("km^2/s")), \
        vbu(N) & = vecrow(-9500, 30000, 0) space (unit("km^2/s")), \
        vbu(e) & = vecrow(-0.1910373697, 0.0102691021, 0.1138093863), \
        cal(E) & = qty(result("03a", "energy"), "km^2/s^2").
    $

    Here $N_x<0$ and $N_y>0$, so $Omega$ lies in the second quadrant.

    Also, $v_r=qty(result("03a", "vr"), "km/s")>0$, so the satellite is moving away from perigee.

    Using the relations in #link(<hwk:s01a>)[Problem 1, Part A] gives:
    $
            e & = #result("03a", "e"), \
            a & = qty(result("03a", "a"), "km"), \
            i & = qty(result("03a", "i"), "degree"), \
        Omega & = qty(result("03a", "Omega"), "degree"), \
        omega & = qty(result("03a", "omega"), "degree"), \
        theta & = qty(result("03a", "theta"), "degree") quad qed
    $
<hwk:s03a>

+ From the true anomaly and eccentricity and the relations in #link(<hwk:s01b>)[Problem 1, Part B], we obtain:
    $
        E & = qty(result("03a", "E"), "degree"), \
        M & = qty(result("03a", "M"), "degree").
    $

    The longitude of perigee is $Omega+omega=qty(179.929860, "degree")$.

    Thus, applying #link(<eqn:equinoctial>)[the equinoctial definitions] gives:
    $
             a & = qty(result("03b", "a"), "km"), \
             h & = #result("03b", "h"), \
             k & = #result("03b", "k"), \
             p & = #result("03b", "p"), \
             q & = #result("03b", "q"), \
        lambda & = qty(result("03b", "lambda"), "degree") quad qed
    $
<hwk:s03b>

#pagebreak(weak: true)

#prob(title: "Curtis 4.6")[
    With respect to the geocentric equatorial frame, the position vector of a spacecraft is $vbu(r) = - 6000 vuu(I) - 1000 vuu(J) - 5000 vuu(K) space (unit("km"))$ and the orbit's eccentricity vector is $vbu(e) = -0.4 vuu(I) + -0.5 vuu(J) + -0.6 vuu(K)$. Calculate the true anomaly $theta$ if the satellite is approaching perigee.
] <hwk:p04>

The eccentricity vector points toward perigee, so:
$
    cos(theta)= (vbu(e) dot vbu(r))/(e r).
$

The required magnitudes and dot product are:
$
    e & = sqrt(0.4^2+0.5^2+0.6^2)=#result("04", "e"), \
    r & = sqrt(6000^2+1000^2+5000^2) space unit("km") = qty(result("04", "r"), "km"), \
    vbu(e) dot vbu(r) & = -qty(5900, "km").
$

Thus, we have:
$
            cos(theta) & = #result("04", "cos theta"), \
    arccos(cos(theta)) & = qty(result("04", "principal"), "degree").
$

Unfortunately, the inverse cosine alone does not distinguish the inbound and outbound branches.

Since $v_r=(mu/H)e sin(theta)<0$ when approaching perigee, $theta$ is bounded by $qty(180, "degree")<theta<qty(360, "degree")$.

Therefore, the true anomaly is:
$
    theta & = qty(360, "degree")-qty(result("04", "principal"), "degree") \
          & = qty(result("04", "theta"), "degree") quad qed
$
<hwk:s04>

#pagebreak(weak: true)

#prob(title: "Curtis 4.7")[
    Given that, relative to the geocentric equatorial frame, $vbu(r) = - 6600 vuu(I) - 1300 vuu(J) - 5200 vuu(K) space (unit("km"))$, the eccentricity vector is $vbu(e) = - 0.4 vuu(I) - 0.5 vuu(J) - 0.6 vuu(K)$, and the satellite is flying toward perigee, calculate the inclination of the orbit.
] <hwk:p05>

Both $vbu(r)$ and $vbu(e)$ lie in the orbital plane, so their cross product determines the normal up to its sign.

With $theta$ measured in the direction of motion, the cross product is:
$
    vbu(e) times vbu(r)=e r sin(theta) vuu(H).
$

The satellite is flying toward perigee, so $sin(theta)<0$.

Therefore, the unit angular momentum vector is:
$
    vuu(H)=(vbu(r) times vbu(e))/(abs(vbu(r) times vbu(e))).
$

Computing the cross product gives:
$
    vbu(r) times vbu(e)
    &= det(mat(vuu(I), vuu(J), vuu(K); -6600, -1300, -5200; -0.4, -0.5, -0.6)) \
    &= vecrow(-1820, -1880, 2780) space (unit("km")), \
    abs(vbu(r) times vbu(e))&=qty(result("05", "cross magnitude"), "km").
$

The inclination is the angle between $vuu(H)$ and $vuu(K)$:
$
    cos(i)=vuu(H) dot vuu(K)
    =2780/sqrt(1820^2+1880^2+2780^2)=#result("05", "cos i").
$

Thus, the inclination of the orbit is:
$
    i=arccos(#result("05", "cos i"))=qty(result("05", "i"), "degree") quad qed
$
<hwk:s05>

#pagebreak(weak: true)

#prob(title: "")[
    Find the equinoctial elements for the following orbits:

    + Position and Velocity:
        $
            vbu(r) = mat(3698.3455; -34232.4473; 0) space (unit("km")), quad
            vbu(v) = mat(2.1482; -1.4944; 0) space (unit("km/s"))
        $
    <hwk:p06a>

    + Position and Velocity:
        $
            vbu(r) = mat(-21082.0848; 36515.242; 0) space (unit("km")), quad
            vbu(v) = mat(-2.6627; -1.5373; 0) space (unit("km/s"))
        $
    <hwk:p06b>

    + Position and Velocity:
        $
            vbu(r) = mat(-15843.4562; -2247.7766; 21200.4627) space (unit("km")), quad
            vbu(v) = mat(1.4544; -3.5188; 0.7138) space (unit("km/s"))
        $
    <hwk:p06c>
] <hwk:p06>

+ The orbit is equatorial and prograde because $H_x=H_y=0$ and $H_z>0$.

    Thus, $i=0$ and $p=q=0$.

    Although the ascending node is undefined, the longitude of perigee $pi.alt=Omega+omega$ is well defined for this eccentric orbit.

    In the equatorial plane, the eccentricity vector gives $k=e_x$ and $h=e_y$:
    $
        vbu(e) & = vecrow(-0.3623940235, 0.6276769176, 0), \
             e & = #result("06a", "e").
    $

    We can obtain the true longitude directly from position via:
    $
        L = theta + omega + Omega = op("atan2")(r_y,r_x)=qty(result("06a", "L"), "degree").
    $

    We now require the equinoctial eccentric longitude and the parameter $beta$:
    $
           F & = pi.alt+E \
        beta & = 1/(1+sqrt(1-h^2-k^2)).
    $

    With $1/beta=1+sqrt(1-h^2-k^2)$, the eccentric longitude is:
    $
        F & = L+2op("atan2")(h cos(L)-k sin(L),1/beta+k cos(L)+h sin(L)).
    $ <eqn:longitude>

    Recall that $lambda=pi.alt+E-e sin(E)$, meaning:
    $
        lambda & = F+h cos(F)-k sin(F).
    $

    After reducing $lambda mod 2pi$, the equinoctial elements are:
    $
             a & = qty(result("06a", "a"), "km"), \
             h & = #result("06a", "h"), \
             k & = #result("06a", "k"), \
             p & = 0, \
             q & = 0, \
        lambda & = qty(result("06a", "lambda"), "degree") quad qed
    $
<hwk:s06a>

+ Again, $H_x=H_y=0$ and $H_z>0$, so $p=q=0$, $h=e_y$, and $k=e_x$.

    Computing directly from the given state gives:
    $
        e & = #result("06b", "e") \
        L & = qty(result("06b", "L"), "degree").
    $

    This orbit is nearly circular. Retaining the small eccentricity from the supplied rounded state, and using #link(<eqn:longitude>)[the longitude equations], gives:
    $
             a & = qty(result("06b", "a"), "km"), \
             h & = #result("06b", "h"), \
             k & = #result("06b", "k"), \
             p & = 0, \
             q & = 0, \
        lambda & = qty(result("06b", "lambda"), "degree") quad qed
    $

    In the circular limit, $h=k=0$ and $lambda=L$, so no perigee direction is needed.
<hwk:s06b>

+ For an inclined orbit, we obtain $p$ and $q$ directly from angular momentum:
    $
        p=H_x/(H+H_z), quad q=-H_y/(H+H_z).
    $

    Let $s=1+p^2+q^2$ and introduce the orthonormal axes in the orbital plane
    $
        vuu(f) & =1/s vecrow(1-p^2+q^2, 2p q, -2p), \
        vuu(g) & =1/s vecrow(2p q, 1+p^2-q^2, 2q).
    $

    These reduce to $vuu(I)$ and $vuu(J)$ when $p=q=0$. In this basis,
    $
        k & = vbu(e) dot vuu(f), \
        h & = vbu(e) dot vuu(g), \
        L & = op("atan2")(vbu(r) dot vuu(g), vbu(r) dot vuu(f)).
    $
    Substitution gives:
    $
        vbu(H) & =vecrow(72995.725212, 42143.011986, 59019.119964) space (unit("km^2/s")), \
        e & =#result("06c", "e"), \
        L&=qty(result("06c", "L"), "degree").
    $

    Using #link(<eqn:longitude>)[the longitude equations] and the energy relation for $a$, the equinoctial elements are:
    $
             a & = qty(result("06c", "a"), "km"), \
             h & = #result("06c", "h"), \
             k & = #result("06c", "k"), \
             p & = #result("06c", "p"), \
             q & = #result("06c", "q"), \
        lambda & = qty(result("06c", "lambda"), "degree") quad qed
    $
    This orbit is also nearly circular. The small nonzero values of $h$ and $k$ are retained rather than setting them to zero.
<hwk:s06c>

#pagebreak(weak: true)

== Code

#codly(header: [./src/index.py])
#raw(read("../src/index.py"), block: true, lang: "python") <code:index.py>
